// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KDOS.Data.Models;

public partial class CustomsDeclaration
{
    public int Id { get; set; }

    public string Sender { get; set; }

    public string Receiver { get; set; }

    public string CustomsAgent { get; set; }

    public string Transportation { get; set; }

    public int OrderId { get; set; }

    public DateOnly? InspectionDate { get; set; }

    public string ImportPermit { get; set; }

    public bool? QuarantineRequired { get; set; }

    public decimal? CustomsFee { get; set; }

    public string Status { get; set; }

    public int? SenderCustomerId { get; set; }

    public int? ReceiverCustomerId { get; set; }

    public virtual Order Order { get; set; }

    public virtual Customer ReceiverCustomer { get; set; }

    public virtual Customer SenderCustomer { get; set; }
}