// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KDOS.Data.Models;

public partial class Customer
{
    public int Id { get; set; }

    public string CustomerName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public string Password { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();
    public virtual ICollection<CustomsDeclaration> CustomsDeclarationReceiverCustomers { get; set; } = new List<CustomsDeclaration>();

    public virtual ICollection<CustomsDeclaration> CustomsDeclarationSenderCustomers { get; set; } = new List<CustomsDeclaration>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}