// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace KDOS.Data.Models;

public partial class FishHealth
{
    public int Id { get; set; }

    [Required]
    public int OrderDetailsId { get; set; }

    public int? OrderId { get; set; }
    public decimal? Temperature { get; set; }

    public decimal? OxygenLevel { get; set; }

    public decimal? PHLevel { get; set; }

    public decimal? AmmoniaLevel { get; set; }

    public DateTime HealthCheckDate { get; set; }

    public string? HealthStatus { get; set; }

    public string? Notes { get; set; }
    public virtual Order? Order { get; set; }

    public virtual OrderDetail? OrderDetails { get; set; }
}
