// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KDOS.Data.Models;

public partial class Notification
{
    public int Id { get; set; }

    public string NotificationType { get; set; }

    public string Message { get; set; }

    public DateOnly NotificationDate { get; set; }

    public string Status { get; set; }

    public string EntityType { get; set; }

    public int EntityId { get; set; }
}