// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KDOS.Data.Models;

public partial class Payment
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int CustomerId { get; set; }

    public DateOnly PaymentDate { get; set; }

    public decimal? AmountPaid { get; set; }

    public string PaymentMethod { get; set; }

    public string TransactionId { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Order Order { get; set; }
}