// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KDOS.Data.Models;

public partial class PriceList
{
    public int Id { get; set; }

    public int Quantity { get; set; }

    public decimal? WeightMinRange { get; set; }

    public decimal? WeightMaxRange { get; set; }

    public string ShippingMethod { get; set; }

    public decimal BasePrice { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}