// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KDOS.Data.Models;

public partial class Staff
{
    public int Id { get; set; }

    public string StaffName { get; set; }

    public string Role { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Password { get; set; }

    public virtual ICollection<Packing> Packings { get; set; } = new List<Packing>();
}