// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KDOS.Data.Models;

public partial class Transport
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public string Location { get; set; }

    public string CurrentStatus { get; set; }

    public virtual Order Order { get; set; }
}